listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

http_api {
    enabled         on;
    listen          1985;
}

vhost __defaultVhost__ {
    min_latency     on;
    play {
        gop_cache   off;
        queue_length 10;
    }
}
